# coding: utf-8

"""
    greptile-codex-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MockReviewsMockUpdateReviewRequest(BaseModel):
    """
    MockReviewsMockUpdateReviewRequest
    """ # noqa: E501
    body: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2000)]] = None
    customer_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    product_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    rating: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = None
    title: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=120)]] = None
    __properties: ClassVar[List[str]] = ["body", "customer_id", "product_id", "rating", "title"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MockReviewsMockUpdateReviewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MockReviewsMockUpdateReviewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "body": obj.get("body"),
            "customer_id": obj.get("customer_id"),
            "product_id": obj.get("product_id"),
            "rating": obj.get("rating"),
            "title": obj.get("title")
        })
        return _obj


