# coding: utf-8

"""
    greptile-codex-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MockProductsMockUpdateProductRequest(BaseModel):
    """
    MockProductsMockUpdateProductRequest
    """ # noqa: E501
    active: Optional[StrictBool] = None
    category: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=80)]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    name: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=120)]] = None
    price_cents: Optional[Annotated[int, Field(le=100000000, strict=True, ge=0)]] = None
    sku: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=40)]] = None
    stock_quantity: Optional[Annotated[int, Field(le=10000000, strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["active", "category", "description", "name", "price_cents", "sku", "stock_quantity"]

    @field_validator('sku', mode="before")
    def sku_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MockProductsMockUpdateProductRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MockProductsMockUpdateProductRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "category": obj.get("category"),
            "description": obj.get("description"),
            "name": obj.get("name"),
            "price_cents": obj.get("price_cents"),
            "sku": obj.get("sku"),
            "stock_quantity": obj.get("stock_quantity")
        })
        return _obj


