# coding: utf-8

"""
    greptile-codex-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemHealthHealthGetResponse(BaseModel):
    """
    SystemHealthHealthGetResponse
    """ # noqa: E501
    environment: StrictStr = Field(description="Which deployment answered: development, demo or production.")
    service: StrictStr = Field(description="The service's own name, for multi-service dashboards.")
    status: StrictStr = Field(description="`ok` when the service is serving traffic, `degraded` otherwise.")
    storage: StrictStr = Field(description="The storage backend currently in use.")
    timestamp: datetime = Field(description="When this answer was produced, in UTC.")
    version: StrictStr = Field(description="The running application version.")
    __properties: ClassVar[List[str]] = ["environment", "service", "status", "storage", "timestamp", "version"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ok', 'degraded']):
            raise ValueError("must be one of enum values ('ok', 'degraded')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemHealthHealthGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemHealthHealthGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "environment": obj.get("environment"),
            "service": obj.get("service"),
            "status": obj.get("status"),
            "storage": obj.get("storage"),
            "timestamp": obj.get("timestamp"),
            "version": obj.get("version")
        })
        return _obj


