# coding: utf-8

"""
    greptile-codex-backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TasksDeleteTaskApiV1TasksTaskIdDeleteRequest(BaseModel):
    """
    TasksDeleteTaskApiV1TasksTaskIdDeleteRequest
    """ # noqa: E501
    created_at: datetime
    description: Optional[StrictStr] = None
    due_at: Optional[datetime] = None
    id: StrictStr
    owner_id: StrictStr
    priority: Optional[StrictStr] = None
    project_id: StrictStr
    status: Optional[StrictStr] = None
    title: StrictStr
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["created_at", "description", "due_at", "id", "owner_id", "priority", "project_id", "status", "title", "updated_at"]

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'critical']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['todo', 'in_progress', 'done']):
            raise ValueError("must be one of enum values ('todo', 'in_progress', 'done')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TasksDeleteTaskApiV1TasksTaskIdDeleteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TasksDeleteTaskApiV1TasksTaskIdDeleteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "due_at": obj.get("due_at"),
            "id": obj.get("id"),
            "owner_id": obj.get("owner_id"),
            "priority": obj.get("priority"),
            "project_id": obj.get("project_id"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


